#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nss-pam-ldapd
Version  : 0.9.10
Release  : 2
URL      : https://github.com/arthurdejong/nss-pam-ldapd/archive/0.9.10.tar.gz
Source0  : https://github.com/arthurdejong/nss-pam-ldapd/archive/0.9.10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: nss-pam-ldapd-bin
Requires: nss-pam-ldapd-lib
Requires: nss-pam-ldapd-license
Requires: nss-pam-ldapd-data
BuildRequires : Linux-PAM-dev
BuildRequires : cyrus-sasl-dev
BuildRequires : krb5-dev
BuildRequires : openldap-dev

%description
nss-pam-ldapd - NSS and PAM libraries for name lookups and authentication
using LDAP

%package bin
Summary: bin components for the nss-pam-ldapd package.
Group: Binaries
Requires: nss-pam-ldapd-data = %{version}-%{release}
Requires: nss-pam-ldapd-license = %{version}-%{release}

%description bin
bin components for the nss-pam-ldapd package.


%package data
Summary: data components for the nss-pam-ldapd package.
Group: Data

%description data
data components for the nss-pam-ldapd package.


%package lib
Summary: lib components for the nss-pam-ldapd package.
Group: Libraries
Requires: nss-pam-ldapd-data = %{version}-%{release}
Requires: nss-pam-ldapd-license = %{version}-%{release}

%description lib
lib components for the nss-pam-ldapd package.


%package license
Summary: license components for the nss-pam-ldapd package.
Group: Default

%description license
license components for the nss-pam-ldapd package.


%prep
%setup -q -n nss-pam-ldapd-0.9.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537572296
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1537572296
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/nss-pam-ldapd
cp COPYING %{buildroot}/usr/share/doc/nss-pam-ldapd/COPYING
%make_install

%files
%defattr(-,root,root,-)
/lib/security/pam_ldap.so

%files bin
%defattr(-,root,root,-)
/usr/bin/chsh.ldap
/usr/bin/getent.ldap
/usr/bin/nslcd

%files data
%defattr(-,root,root,-)
/usr/share/nslcd-utils/chsh.py
/usr/share/nslcd-utils/cmdline.py
/usr/share/nslcd-utils/constants.py
/usr/share/nslcd-utils/getent.py
/usr/share/nslcd-utils/nslcd.py
/usr/share/nslcd-utils/shells.py
/usr/share/nslcd-utils/users.py

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnss_ldap.so.2

%files license
%defattr(-,root,root,-)
/usr/share/doc/nss-pam-ldapd/COPYING
